# app/config/admin.yml
services:
    pn.pn.admin.job:
        class: Pn\PnBundle\Admin\JobAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: jobs, label: Jobs }
        arguments:
        - ~
        - Pn\PnBundle\Entity\Job
        - ~

    pn.pn.admin.babysitter:
        class: Pn\PnBundle\Admin\BabysitterAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: users, label: Babysitters }
        arguments: [null, Pn\PnBundle\Entity\Babysitter, PnPnBundle:BabysitterAdmin]

    pn.pn.admin.pparent:
        class: Pn\PnBundle\Admin\PparentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: users, label: Parents }
        arguments: [null, Pn\PnBundle\Entity\Pparent, PnPnBundle:PparentAdmin]

    pn.pn.admin.mooc:
        class: Pn\PnBundle\Admin\MoocAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: formations, label: Formations }
        arguments: [null, Pn\PnBundle\Entity\Mooc, PnPnBundle:MoocAdmin]

    pn.pn.admin.mailtemplate:
        class: Pn\PnBundle\Admin\MailTemplateAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: emails, label: Emails }
        arguments: [null, Pn\PnBundle\Entity\MailTemplate, PnPnBundle:MailTemplateAdmin]

    pn.pn.admin.recommendation:
        class: Pn\PnBundle\Admin\RecommendationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: users, label: Recommendations }
        arguments: [null, Pn\PnBundle\Entity\Recommendation, PnPnBundle:RecommendationAdmin]

    sonata.block.service.statistics:
        class: Pn\PnBundle\Block\Service\StatisticsBlockService
        tags:
            - { name: sonata.block }
        arguments:
            - "sonata.block.service.statistics"
            - @templating
            - @doctrine.orm.entity_manager

    sonata.block.service.connected.user:
        class: Pn\PnBundle\Block\Service\ConnectedUserBlockService
        tags:
            - { name: sonata.block }
        arguments:
            - "sonata.block.service.connected.user"
            - @templating
            - @security.context

    sonata.block.service.controls:
        class: Pn\PnBundle\Block\Service\ControlsBlockService
        tags:
            - { name: sonata.block }
        arguments:
            - "sonata.block.service.controls"
            - @templating
            - @security.context