pn_pn_homepage:
    pattern:  /
    defaults: { _controller: PnPnBundle:Default:index }

pn_pn_default:
    resource: "@PnPnBundle/Resources/config/routing/default.yml"
    prefix:   /

pn_pn_jobs:
    resource: "@PnPnBundle/Resources/config/routing/job.yml"
    prefix:   /job

PnPnBundle_user:
    resource: "@PnPnBundle/Resources/config/routing/user.yml"
    prefix:   /user

PnPnBundle_babysitter:
    resource: "@PnPnBundle/Resources/config/routing/babysitter.yml"
    prefix:   /babysitter

PnPnBundle_parent:
    resource: "@PnPnBundle/Resources/config/routing/pparent.yml"
    prefix:   /pparent

PnPnBundle_dashboard:
    resource: "@PnPnBundle/Resources/config/routing/dashboard.yml"
    prefix:   /dashboard

PnPnBundle_mooc:
    resource: "@PnPnBundle/Resources/config/routing/mooc.yml"
    prefix:   /mooc

PnPnBundle_message:
    resource: "@PnPnBundle/Resources/config/routing/message.yml"
    prefix:   /message

PnPnBundle_recommendation:
    resource: "@PnPnBundle/Resources/config/routing/recommendation.yml"
    prefix:   /recommendation


