parameters:
#    pn_pn.example.class: Pn\PnBundle\Example
    mailer.from: contact@parent-nounou.fr

    # Trustpoints Profile
    trustpoints.profile.firstname: 2
    trustpoints.profile.lastname: 2
    trustpoints.profile.birthdate: 2
    trustpoints.profile.postcode: 2
    trustpoints.profile.city: 2
    trustpoints.profile.address: 2
    trustpoints.profile.phone: 2
    trustpoints.profile.avatar: 10
    trustpoints.profile.extraPicture: 3

    # trustpoints babysitter
    trustpoints.babysitter.children: 1
    trustpoints.babysitter.favoriteActivity: 1
    trustpoints.babysitter.languages: 1
    trustpoints.babysitter.hobbies: 1
    trustpoints.babysitter.smoke: 1
    trustpoints.babysitter.drvingLicense: 1
    trustpoints.babysitter.car: 1
    trustpoints.babysitter.pets: 1
    trustpoints.babysitter.recommandations: 1
    trustpoints.babysitter.presentation: 3
    trustpoints.babysitter.experience: 2
    trustpoints.babysitter.diplomas: 1
    trustpoints.babysitter.category: 2
    trustpoints.babysitter.ageOfChildren: 1
    trustpoints.babysitter.calendar: 3
    trustpoints.babysitter.priceRate: 1
    trustpoints.babysitter.checkID: 10
    trustpoints.babysitter.checkAge: 10
    trustpoints.babysitter.checkPhone: 15
    trustpoints.babysitter.checkEmail: 15
    trustpoints.babysitter.checkDiplomas: 10

    #  Ballons
    baloon.1: 10    # >=10
    baloon.2: 20    # >=20
    baloon.3: 30    # >=30
    baloon.4: 40    # >=40
    baloon.5: 50    # >=50



services:

    pn.pn.admin.job:
        class: Pn\PnBundle\Admin\JobAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: jobs, label: Jobs }
        arguments: [null, Pn\PnBundle\Entity\Job, PnPnBundle:JobAdmin]

    pn.pn.admin.user:
        class: Pn\PnBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: users, label: Utilisateurs }
        arguments: [null, Pn\PnBundle\Entity\User, PnPnBundle:UserAdmin]

    pn.pn.admin.babysitter:
        class: Pn\PnBundle\Admin\BabysitterAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: users, label: Babysitters }
        arguments: [null, Pn\PnBundle\Entity\Babysitter, PnPnBundle:BabysitterAdmin]

    pn.pn.admin.pparent:
        class: Pn\PnBundle\Admin\PparentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: users, label: Parents }
        arguments: [null, Pn\PnBundle\Entity\Pparent, PnPnBundle:PparentAdmin]

    pn.pn.admin.mooc:
        class: Pn\PnBundle\Admin\MoocAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: formations, label: Formations }
        arguments: [null, Pn\PnBundle\Entity\Mooc, PnPnBundle:MoocAdmin]

    pn.pn.admin.mailtemplate:
        class: Pn\PnBundle\Admin\MailTemplateAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: emails, label: Emails }
        arguments: [null, Pn\PnBundle\Entity\MailTemplate, PnPnBundle:MailTemplateAdmin]

    pn.calendar:
        class: Pn\PnBundle\Services\Calendar

    pn.crop:
        class: Pn\PnBundle\Services\Crop