# src/Pn/PnBundle/Resources/config/validation.yml

Pn\PnBundle\Entity\Job:
    properties:
        rate_type:
            - NotBlank: ~
            - Choice: { callback: getTypeValues }
        title:
            - NotBlank: ~
        description:
            - NotBlank: ~
        rate_type:
            - NotBlank: ~

Pn\PnBundle\Entity\Babysitter:
    properties:
        file:
            - Image: ~