parameters:
#    pn_pages.example.class: Pn\PagesBundle\Example

services:
#    pn_pages.example:
#        class: %pn_pages.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
