services:
    application.sonata.news.form.type.comment:
        class: Application\Sonata\NewsBundle\Form\Type\CommentType
        tags:
            -  { name: form.type, alias: application_sonata_post_comment }