# src/Pn/PnBundle/Resources/config/doctrine/Babysitter.orm.yml
Pn\PnBundle\Entity\Babysitter:
  type: entity
  repositoryClass: Pn\PnBundle\Repository\BabysitterRepository
  table: babysitter
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    presentation:
      type: text
      nullable: true
    rate_price:
      type: decimal
      nullable: true
    rate_type:
      type: string
      length: 255
      nullable: true
    avatar:
      type: string
      length: 255
      nullable: true
    video:
      type: string
      length: 255
      nullable: true
    experience:
      type: integer
      nullable: true
    trustpoints:
      type: integer
      nullable: true
    anythingelse:
      type: text
      nullable: true
    ageofchildren:
      type: string
      length: 255
      nullable: true
    favoriteactivities:
      type: text
      nullable: true
    hobbies:
      type: text
      nullable: true
    mychildren:
      type: string
      length: 255
      nullable: true
    calendar:
      type: string
      length: 255
      nullable: true
    category:
      type: string
      length: 255
      nullable: true
    petitsplus:
      type: array
      nullable: true
    particularite:
        type: array
        nullable: true
  oneToOne:
    user:
      targetEntity: User
      inversedBy: babysitter
      joinColumn:
        name: user_id
        referencedColumnName: id
  lifecycleCallbacks:
    prePersist: [ preUpload, setDefaultValues ]
    preUpdate: [ preUpload ]
    postPersist: [ upload ]
    postUpdate: [ upload ]
    postRemove: [ removeUpload ]