# src/Pn/PnBundle/Resources/config/doctrine/Job.orm.yml
Pn\PnBundle\Entity\Job:
  type: entity
  repositoryClass: Pn\PnBundle\Repository\JobRepository
  table: job
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    title:
      type: string
      length: 255
      nullable: true
    status:
      type: string
      length: 255
      nullable: true
    presentation:
      type: text
      nullable: true
    address:
      type: string
      length: 255
      nullable: true
    unacurateAddress:
      type: string
      length: 255
      nullable: true
    postcode:
      type: string
      length: 255
      nullable: true
    departement:
      type: string
      length: 255
      nullable: true
    city:
      type: string
      length: 255
      nullable: true
    latitude:
      type: decimal
      length: 10
      scale: 8
      nullable: true
    longitude:
      type: decimal
      length: 10
      scale: 8
      nullable: true
    rate_price:
      type: decimal
      length: 5
      scale: 2
      nullable: true
    rate_type:
      type: string
      length: 255
      nullable: true
    duration:
      type: string
      length: 255
      nullable: true
    how_to_apply:
      type: text
      nullable: true
    calendar:
      type: string
      length: 255
      nullable: true
    is_public:
      type: boolean
      nullable: true
    is_activated:
      type: boolean
      nullable: true
    expires_at:
      type: datetime
      nullable: true
    created_at:
      type: datetime
    updated_at:
      type: datetime
      nullable: true
    category:
      type: string
      length: 255
      nullable: true
    experience:
      type: integer
      nullable: true
    start:
      type: date
      nullable: true
    end:
      type: date
      nullable: true
    diplomas:
      type: array
      nullable: true
    ageofchildren:
      type: array
      nullable: true
    languages:
      type: array
      nullable: true
    petitsplus:
      type: array
      nullable: true
    extraTasks:
      type: array
      nullable: true
    particularite:
      type: array
      nullable: true
    phone:
      type: string
      length: 255
      nullable: true
  manyToOne:
    parent:
      targetEntity: Pparent
      inversedBy: jobs
      joinColumn:
        name: parent_id
        referencedColumnName: id
  lifecycleCallbacks:
    prePersist: [ setCreatedAtValue, setDefaultValues ]
    preUpdate: [ setUpdatedAtValue ]