# src/Pn/PnBundle/Resources/config/doctrine/Message.orm.yml
Pn\PnBundle\Entity\Message:
  type: entity
  repositoryClass: Pn\PnBundle\Repository\MessageRepository
  table: message
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    status:
      type: string
      length: 255
      nullable: true
    body:
      type: text
      nullable: true
    created_at:
      type: datetime
  manyToOne:
    sender:
      targetEntity: User
      inversedBy: sent_messages
      joinColumn:
        name: sender_id
        referencedColumnName: id
    receiver:
      targetEntity: User
      inversedBy: received_messages
      joinColumn:
        name: receiver_id
        referencedColumnName: id
  lifecycleCallbacks:
    prePersist: [ setCreatedAtValue ]