# src/Pn/PnBundle/Resources/config/doctrine/User.orm.yml

Pn\PnBundle\Entity\User:
  type: entity
  repositoryClass: Pn\PnBundle\Repository\UserRepository
  table: user
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    username:
      type: string
      length: 255
    password:
      type: string
      length: 255
    rawPassword:
      type: string
      length: 255
      nullable: true
    type:
      type: string
      length: 255
    email:
      type: string
      length: 255
      unique: true
    firstname:
      type: string
      length: 255
      nullable: true
    lastname:
      type: string
      length: 255
      nullable: true
    phone:
      type: string
      length: 255
      nullable: true
    is_activated:
      type: boolean
      nullable: true
    created_at:
      type: datetime
    updated_at:
      type: datetime
      nullable: true
    address:
      type: string
      length: 255
      nullable: true
    latitude:
      type: decimal
      length: 10
      scale: 8
      nullable: true
    longitude:
      type: decimal
      length: 10
      scale: 8
      nullable: true
  oneToOne:
    babysitter:
      targetEntity: Babysitter
      mappedBy: user
      joinColumn:
          onDelete: CASCADE
    parent:
      targetEntity: Pparent
      mappedBy: user
      joinColumn:
          onDelete: CASCADE
  lifecycleCallbacks:
    prePersist: [ setCreatedAtValue, setDefaultValues ]
    preUpdate: [ setUpdatedAtValue ]