# src/Pn/BlogBundle/Resources/config/doctrine/Category.orm.yml
Pn\BlogBundle\Entity\Category:
  type: entity
  table: blog_category
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 255
      unique: true
    icon:
      type: string
      length: 255
  oneToMany:
    articles:
      targetEntity: Article
      mappedBy: category