
babysitter:
    pattern:  /
    defaults: { _controller: PnPnBundle:Babysitter:index }

babysitter_new:
    pattern:  /new
    defaults: { _controller: "PnPnBundle:Babysitter:new" }

babysitter_create:
    pattern:  /create
    defaults: { _controller: "PnPnBundle:Babysitter:create" }
    requirements: { _method: post }

babysitter_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "PnPnBundle:Babysitter:edit" }

babysitter_update:
    pattern:  /{id}/update
    defaults: { _controller: "PnPnBundle:Babysitter:update" }
    requirements: { _method: post|put }

babysitter_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "PnPnBundle:Babysitter:delete" }
    requirements: { _method: post|delete }

babysitter_update_field:
    pattern:  /{id}/update_field
    defaults: { _controller: "PnPnBundle:Babysitter:updateField" }
    requirements: { _method: post|put }

babysitter_updateCalendarAJAX:
    pattern:  /{id}/updateCalendarAJAX
    defaults: { _controller: "PnPnBundle:Babysitter:updateCalendarAJAX" }
    requirements: { _method: post|put }

pn_babysitter_updateAddress:
    pattern:  /{id}/updateAddress
    defaults: { _controller: "PnPnBundle:Babysitter:updateAddressAJAX" }
    requirements: { _method: post|put }

pn_babysitter_videoUpload:
    pattern:  /videoUpload
    defaults: { _controller: "PnPnBundle:Babysitter:videoUploadAJAX" }
    requirements: { _method: post|put }

pn_babysitter_presentationAJAX:
    pattern:  /presentationAJAX
    defaults: { _controller: "PnPnBundle:Babysitter:presentationAJAX" }
    requirements: { _method: post|put|get }

pn_babysitter_updateTrustpoints:
    pattern:  /updateTrustpoints
    defaults: { _controller: "PnPnBundle:Babysitter:updateAllTrustpoints" }