
myprofile_show:
    pattern:   /myprofile/show
    defaults:  { _controller: PnPnBundle:Default:myprofileView }

myprofile_edit:
    pattern:   /myprofile/edit
    defaults:  { _controller: PnPnBundle:Default:myprofileEdit }

pn_search:
    pattern:   /search
    defaults:  { _controller: PnPnBundle:Default:search }

pn_contact:
    pattern:   /contact
    defaults:  { _controller: PnPnBundle:Default:contact }

pn_team:
    pattern:   /team
    defaults:  { _controller: PnPnBundle:Default:team }