
pn_job:
    pattern:  /
    defaults: { _controller: "PnPnBundle:Job:index" }

pn_job_new:
    pattern:  /new
    defaults: { _controller: "PnPnBundle:Job:new" }

pn_job_create:
    pattern:  /create
    defaults: { _controller: "PnPnBundle:Job:create" }
    requirements: { _method: post }

pn_job_update:
    pattern:  /{id}/update
    defaults: { _controller: "PnPnBundle:Job:update" }
    requirements: { _method: post|put }

pn_job_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "PnPnBundle:Job:delete" }
    requirements: { _method: post|delete }

pn_job_annonces:
    pattern:  /annonces
    defaults: { _controller: "PnPnBundle:Job:annonces" }

pn_job_updateAddress:
    pattern:  /{id}/updateAddress
    defaults: { _controller: "PnPnBundle:Job:updateAddressAJAX" }
    requirements: { _method: post|put }

pn_job_updateField:
    pattern:  /{id}/updateField
    defaults: { _controller: "PnPnBundle:Job:updateFieldAJAX" }
    requirements: { _method: post|put }

pn_job_updateCalendar:
    pattern:  /{id}/updateCalendar
    defaults: { _controller: "PnPnBundle:Job:updateCalendarAJAX" }
    requirements: { _method: post|put|get }

pn_job_presentationAJAX:
    pattern:  /presentationAJAX
    defaults: { _controller: "PnPnBundle:Job:presentationAJAX" }
    requirements: { _method: post|put|get }