
message_send:
    pattern:  /send/{to}
    defaults: { _controller: "PnPnBundle:Message:send" }
    requirements: { _method: post }

pn_new_conversation:
    pattern:  /new_conversation
    defaults: { _controller: "PnPnBundle:Message:newConversation" }
    requirements: { _method: post }

message:
    pattern:  /{conv}
    defaults: { _controller: "PnPnBundle:Message:index", conv: null }
