parameters:
#    pn_blog.example.class: Pn\BlogBundle\Example

services:

    pn.pn.admin.category:
        class: Pn\BlogBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: blog, label: Category }
        arguments: [null, Pn\BlogBundle\Entity\Category, PnBlogBundle:CategoryAdmin]

    pn.pn.admin.article:
        class: Pn\BlogBundle\Admin\ArticleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: blog, label: Article }
        arguments: [null, Pn\BlogBundle\Entity\Article, PnBlogBundle:ArticleAdmin]