parameters:
#    pn_blog.example.class: Pn\BlogBundle\Example

services:
#    pn_blog.example:
#        class: %pn_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    pn.blog.admin.post:
          class: Pn\BlogBundle\Admin\PostAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: pn_blog, label: post }
          arguments: [null, Pn\BlogBundle\Entity\Post, PnBlogBundle:PostAdmin]

    pn.blog.admin.tag:
          class: Pn\BlogBundle\Admin\TagAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: pn_blog, label: tag }
          arguments: [null, Pn\BlogBundle\Entity\Tag, PnBlogBundle:TagAdmin]

    pn.blog.admin.comment:
          class: Pn\BlogBundle\Admin\CommentAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: pn_blog, label: comment }
          arguments: [null, Pn\BlogBundle\Entity\Comment, PnBlogBundle:CommentAdmin]

